# Imports

In [94]:
import torch
import numpy as np

# GPU check

In [95]:
torch.__version__

'2.4.0+cu124'

In [96]:
!nvidia-smi

Wed Jul 31 14:46:11 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.42.06              Driver Version: 532.10         CUDA Version: 12.1     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...    On  |   00000000:01:00.0 Off |                  N/A |
| N/A   39C    P8              1W /  N/A  |       0MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [97]:
torch.cuda.is_available()

True

In [98]:
torch.cuda.get_device_name()

'NVIDIA GeForce RTX 4060 Laptop GPU'

# Tensor Overview

In [99]:
# scalar tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [100]:
type(scalar), scalar.ndim, scalar.shape

(torch.Tensor, 0, torch.Size([]))

In [101]:
# get tensor as python int
scalar.item()

7

In [102]:
# single dimension
tensor = torch.tensor([7, 7])
tensor

tensor([7, 7])

In [103]:
type(tensor), tensor.ndim, tensor.shape

(torch.Tensor, 1, torch.Size([2]))

In [104]:
# multi dimension tensor
tensor = torch.tensor([[1, 2], [3, 4]])
tensor

tensor([[1, 2],
        [3, 4]])

In [105]:
type(tensor), tensor.ndim, tensor.shape

(torch.Tensor, 2, torch.Size([2, 2]))

In [106]:
# creating multi-dimension tensor from numpy array
np_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

tensor = torch.from_numpy(np_array)
tensor

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [107]:
type(tensor), tensor.ndim, tensor.shape

(torch.Tensor, 2, torch.Size([4, 2]))

In [108]:
# few more ways to create tensors

shape = (2, 3)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [93]:
rand_tensor, ones_tensor, zeros_tensor

(tensor([[0.4329, 0.0623, 0.8836],
         [0.4885, 0.8352, 0.2830]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

## Attributes of a Tensor

In [13]:
tensor = torch.rand(3, 4)

In [109]:
tensor.shape, tensor.dtype, tensor.device

(torch.Size([4, 2]), torch.int64, device(type='cpu'))

## operations on tensors

In [15]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [16]:
tensor.device

device(type='cuda', index=0)

In [17]:
tensor = torch.rand(4, 4)

In [18]:
tensor

tensor([[0.6911, 0.4216, 0.5616, 0.4302],
        [0.0136, 0.6845, 0.8031, 0.1156],
        [0.1104, 0.2213, 0.3059, 0.8381],
        [0.1734, 0.3858, 0.3502, 0.2253]])

In [19]:
tensor[0]

tensor([0.6911, 0.4216, 0.5616, 0.4302])

In [20]:
# first column

tensor[:, 0]

tensor([0.6911, 0.0136, 0.1104, 0.1734])

In [21]:
# last column 

tensor[:, -1]

tensor([0.4302, 0.1156, 0.8381, 0.2253])

In [22]:
# last column 

tensor[..., -1]

tensor([0.4302, 0.1156, 0.8381, 0.2253])

In [23]:
tensor[:, 1] = 0

In [24]:
tensor

tensor([[0.6911, 0.0000, 0.5616, 0.4302],
        [0.0136, 0.0000, 0.8031, 0.1156],
        [0.1104, 0.0000, 0.3059, 0.8381],
        [0.1734, 0.0000, 0.3502, 0.2253]])

In [25]:
# joining the tensors

In [26]:
row_wise_concat = torch.cat([tensor, tensor, tensor], dim=0)
row_wise_concat.shape

torch.Size([12, 4])

In [27]:
row_wise_concat

tensor([[0.6911, 0.0000, 0.5616, 0.4302],
        [0.0136, 0.0000, 0.8031, 0.1156],
        [0.1104, 0.0000, 0.3059, 0.8381],
        [0.1734, 0.0000, 0.3502, 0.2253],
        [0.6911, 0.0000, 0.5616, 0.4302],
        [0.0136, 0.0000, 0.8031, 0.1156],
        [0.1104, 0.0000, 0.3059, 0.8381],
        [0.1734, 0.0000, 0.3502, 0.2253],
        [0.6911, 0.0000, 0.5616, 0.4302],
        [0.0136, 0.0000, 0.8031, 0.1156],
        [0.1104, 0.0000, 0.3059, 0.8381],
        [0.1734, 0.0000, 0.3502, 0.2253]])

In [28]:
column_wise_concat = torch.cat([tensor, tensor, tensor], dim=1)
column_wise_concat.shape

torch.Size([4, 12])

In [29]:
column_wise_concat

tensor([[0.6911, 0.0000, 0.5616, 0.4302, 0.6911, 0.0000, 0.5616, 0.4302, 0.6911,
         0.0000, 0.5616, 0.4302],
        [0.0136, 0.0000, 0.8031, 0.1156, 0.0136, 0.0000, 0.8031, 0.1156, 0.0136,
         0.0000, 0.8031, 0.1156],
        [0.1104, 0.0000, 0.3059, 0.8381, 0.1104, 0.0000, 0.3059, 0.8381, 0.1104,
         0.0000, 0.3059, 0.8381],
        [0.1734, 0.0000, 0.3502, 0.2253, 0.1734, 0.0000, 0.3502, 0.2253, 0.1734,
         0.0000, 0.3502, 0.2253]])

In [30]:
 # arithmetic operations on tensor

y1 = tensor
y1

tensor([[0.6911, 0.0000, 0.5616, 0.4302],
        [0.0136, 0.0000, 0.8031, 0.1156],
        [0.1104, 0.0000, 0.3059, 0.8381],
        [0.1734, 0.0000, 0.3502, 0.2253]])

In [31]:
y2 = tensor.T
y2

tensor([[0.6911, 0.0136, 0.1104, 0.1734],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.5616, 0.8031, 0.3059, 0.3502],
        [0.4302, 0.1156, 0.8381, 0.2253]])

In [32]:
# multiple tensors
y3 = y1 @ y2
y3

tensor([[0.9781, 0.5102, 0.6086, 0.4134],
        [0.5102, 0.6585, 0.3440, 0.3096],
        [0.6086, 0.3440, 0.8081, 0.3150],
        [0.4134, 0.3096, 0.3150, 0.2035]])

In [33]:
# or

y3 = tensor @ tensor.T
y3

tensor([[0.9781, 0.5102, 0.6086, 0.4134],
        [0.5102, 0.6585, 0.3440, 0.3096],
        [0.6086, 0.3440, 0.8081, 0.3150],
        [0.4134, 0.3096, 0.3150, 0.2035]])

In [34]:
# or

y3 = tensor.matmul(tensor.T)
y3

tensor([[0.9781, 0.5102, 0.6086, 0.4134],
        [0.5102, 0.6585, 0.3440, 0.3096],
        [0.6086, 0.3440, 0.8081, 0.3150],
        [0.4134, 0.3096, 0.3150, 0.2035]])